<?php

$products = $this->listSimpleProducts();
?>
 <style type="text/css"> 
 #producttable { 
  width: 100%; 
  border-collapse: collapse; 
}

#producttable tr:nth-of-type(odd) { 
  background: #eee; 
}
#producttable th { 
  background: #333; 
  color: white; 
  font-weight: bold; 
}
#producttable td, th { 
  padding: 6px; 
  border: 1px solid #ccc; 
  text-align: left; 
}
@media 
only screen and (max-width: 760px),
(min-device-width: 768px) and (max-device-width: 1024px)  {

	
	#producttable table, thead, tbody, th, td, tr { 
		display: block; 
	}
	
	
	#producttable thead tr { 
		position: absolute;
		top: -9999px;
		left: -9999px;
	}
	
	#producttable tr { border: 1px solid #ccc; }
	
	#producttable td { 		
		border: none;
		border-bottom: 1px solid #eee; 
		position: relative;
		padding-left: 50%; 
	}
	
	#producttable td:before {		
		position: absolute;		
		top: 6px;
		left: 6px;
		width: 45%; 
		padding-right: 10px; 
		white-space: nowrap;
	}
	
	
	#producttable td:nth-of-type(1):before { content: "Product Name"; }
	#producttable td:nth-of-type(2):before { content: "SKU"; }
	#producttable td:nth-of-type(3):before { content: "Price"; }
	#producttable td:nth-of-type(4):before { content: "Description"; }
	#producttable td:nth-of-type(5):before { content: "Status"; }
	#producttable td:nth-of-type(6):before { content: "Weight"; }
	
}
 </style>
<div id="product_list">
  <h1>Simple Products</h1>
 
  <?php if (is_array($products) && count($products)) { ?>
   <table id="producttable">
	<thead>
	<tr>
		<th>Product Name</th>
		<th>SKU</th>
		<th>Price</th>
		<th>Description</th>
		<th>Status</th>
		<th>Weight</th>
	</tr>
	</thead>
	<tbody>
    <?php foreach($products as $product) { ?>
      <tr>
	  <td><?php echo $product['name'] ?></td>
	  <td><?php echo $product['sku'] ?></td>
	  <td><?php echo $product['price'] ?></td>
	  <td><?php echo $product['description'] ?></td>
	  <td><?php echo $product['status'] ?></td>
	  <td><?php echo $product['weight'] ?></td>	  
	  </tr>       
    <?php } ?>
	</tbody>
</table>
  <?php } ?>
  
</div>